
---
name: "🛠 Refactor"
about: "코드 리팩토링"
labels: ["refactor"]
assignees: []
---

## 📄 리팩토링 설명
<-- 어떤 이유로 리팩토링이 필요한지 작성해주세요. (성능 개선/코드 가독성 향상 등) -->

## 📝 To Do
<!-- 해야 할 일들을 아래 체크박스 형태로 작성해 주세요 -->
- [ ] 

## 🙋🏻 참고 자료
관련된 문서나 링크가 있다면 여기에 작성해주세요.
